const nav=document.querySelector('#nav'); addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>30));
const menu=document.querySelector('.menu-btn'),links=document.querySelector('.links'); menu.onclick=()=>links.classList.toggle('open'); document.querySelectorAll('.links a').forEach(a=>a.onclick=()=>links.classList.remove('open'));
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.12}); document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const grid=document.querySelector('#galleryGrid');
const works=['assets/images/work-01.jpeg','assets/images/work-02.jpeg','assets/images/work-03.jpeg','assets/images/work-04.jpeg','assets/images/work-05.jpeg','assets/images/work-06.jpeg','assets/images/work-07.jpeg','assets/images/work-08.jpeg','assets/images/work-09.jpeg','assets/images/work-10.jpeg','assets/images/work-11.jpeg','assets/images/work-12.jpeg','assets/images/work-13.jpeg','assets/images/work-14.jpeg','assets/images/work-15.jpeg','assets/images/work-16.jpeg','assets/images/work-17.jpeg','assets/images/work-18.jpeg','assets/images/work-19.jpeg','assets/images/work-20.jpeg','assets/images/work-21.jpeg','assets/images/work-22.jpeg','assets/images/work-23.jpeg','assets/images/work-24.jpeg','assets/images/work-25.jpeg','assets/images/work-26.jpeg','assets/images/work-27.jpeg','assets/images/work-28.jpeg','assets/images/work-29.jpeg','assets/images/work-30.jpeg','assets/images/work-31.jpeg','assets/images/work-32.jpeg','assets/images/work-33.jpeg','assets/images/work-34.jpeg','assets/images/work-35.jpeg','assets/images/work-36.jpeg','assets/images/work-37.jpeg','assets/images/work-38.jpeg'];
if(Array.isArray(window.CUSTOM_GALLERY_IMAGES)) works.push(...window.CUSTOM_GALLERY_IMAGES.map(n=>`assets/images/custom/${n}`));
// use the full archive while avoiding a couple of near-duplicate hero-style shots first
function addTile(src,alt='Sthapathi Muthu Selvan work archive'){const d=document.createElement('div');d.className='tile';const img=document.createElement('img');img.src=src;img.loading='lazy';img.alt=alt;img.onerror=()=>{d.remove()};d.appendChild(img);d.onclick=()=>openLightbox(src);grid.appendChild(d)}
works.forEach((src,i)=>addTile(src,`Sthapathi Muthu Selvan work archive ${i+1}`));
const upload=document.querySelector('#photoUpload'); if(upload) upload.addEventListener('change',e=>{[...e.target.files].forEach(file=>{if(!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file);addTile(url,file.name)});});
const lb=document.querySelector('#lightbox'),lbimg=lb.querySelector('img');function openLightbox(src){lbimg.src=src;lb.classList.add('open')}lb.querySelector('button').onclick=()=>lb.classList.remove('open');lb.onclick=e=>{if(e.target===lb)lb.classList.remove('open')};addEventListener('keydown',e=>e.key==='Escape'&&lb.classList.remove('open'));
document.querySelector('#year').textContent=new Date().getFullYear();
